import type { Plan } from '@/types';

export const PLANS: Plan[] = [
  {
    id: 'landing',
    name: 'Landing Express',
    tagline: 'Presencia profesional rápida',
    price: 120,
    currency: 'USD',
    deliveryDays: '3-5',
    features: [
      '1 página optimizada para móviles',
      'Diseño profesional y moderno',
      'Formulario de contacto funcional',
      'Botones WhatsApp, email, teléfono',
      'Integración con redes sociales',
      'Publicación online incluida',
    ],
    ctaLabel: 'Empezar',
  },
  {
    id: 'menu_qr',
    name: 'Menú Digital QR',
    tagline: 'Perfecta para tu restaurante',
    price: 150,
    currency: 'USD',
    deliveryDays: '5-7',
    features: [
      'Menú digital responsive',
      'Hasta 30 productos categorizados',
      'Código QR personalizado',
      'Panel para actualizar precios',
      'Integración WhatsApp para pedidos',
      'Diseño acorde a tu identidad',
    ],
    ctaLabel: 'Empezar',
  },
  {
    id: 'portfolio',
    name: 'Portafolio Pro',
    tagline: 'Tu trabajo en su mejor expresión',
    price: 350,
    currency: 'USD',
    deliveryDays: '10-15',
    highlighted: true,
    features: [
      'Sitio web de 4-6 páginas',
      'Galería con categorías y filtros',
      'Página "Sobre mí" personalizada',
      'Formulario de contacto avanzado',
      'SEO básico incluido',
      'Animaciones y transiciones elegantes',
    ],
    ctaLabel: 'Empezar',
  },
  {
    id: 'restaurant',
    name: 'Restaurante Pro',
    tagline: 'Sitio completo para tu negocio gastronómico',
    price: 500,
    currency: 'USD',
    deliveryDays: '15-20',
    features: [
      'Sitio completo 5-7 páginas',
      'Menú digital con QR incluido',
      'Sistema de reservas online',
      'Galería fotográfica profesional',
      'Mapa interactivo de ubicación',
      'SEO local optimizado',
    ],
    ctaLabel: 'Empezar',
  },
  {
    id: 'custom',
    name: 'Sistema Personalizado',
    tagline: 'Funcionalidades a tu medida',
    price: 900,
    currency: 'USD',
    deliveryDays: '25-45',
    features: [
      'Análisis de requerimientos personalizado',
      'Desarrollo a medida',
      'Panel de administración intuitivo',
      'Capacitación incluida',
      '30 días de soporte post-lanzamiento',
      'Escalable y documentado',
    ],
    ctaLabel: 'Solicitar cotización',
  },
];

export const PLAN_MAP: Record<string, Plan> = Object.fromEntries(PLANS.map((p) => [p.id, p]));
