import type { Plan, PlanFeatureEntry } from '@/types';

// ─── Shared feature-entry helpers ────────────────────────────────────────────
// These keep the per-plan matrices DRY for features that appear across multiple plans.

const f = (
  key: string,
  label: string,
  included: boolean,
  limit?: number | 'unlimited',
  limitUnit?: string,
  note?: string,
): PlanFeatureEntry => ({ key, label, included, limit, limitUnit, note });

// ─── Plan definitions ─────────────────────────────────────────────────────────

export const PLANS: Plan[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // MENÚ DIGITAL QR  ·  $150
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'menu_qr',
    name: 'Menú Digital QR',
    tagline: 'Perfecta para tu restaurante',
    price: 150,
    currency: 'USD',
    deliveryDays: '10-12',
    features: [
      'Diseño visual acorde a tu marca y colores',
      'Hasta 50 platos con foto, descripción y precio',
      'Código QR personalizado listo para imprimir en mesa',
      'Panel sencillo para actualizar platos y precios tú mismo',
      'Botón para que tus clientes pidan directo por WhatsApp',
      'Compatible con cualquier móvil — sin descargar ninguna app',
    ],
    ctaLabel: 'Empezar',
    // ── Matriz de funcionalidades ──
    detailedFeatures: [
      // Páginas / secciones
      f('home', 'Página de inicio del menú', true, 1, 'página'),
      f(
        'menu',
        'Catálogo / menú digital de platos',
        true,
        50,
        'platos',
        'Ampliar a 100 platos requiere upgrade',
      ),
      f(
        'location',
        'Dirección / mapa de ubicación',
        false,
        undefined,
        undefined,
        'No incluido; disponible en plan Restaurante Pro',
      ),
      f('about', 'Página "Sobre nosotros"', false),
      f('contact', 'Página de contacto dedicada', false),
      f('services', 'Página de servicios', false),
      f('pricing', 'Página de precios', false),
      f('testimonials', 'Testimonios / reseñas', false),
      f('blog', 'Sección de blog / noticias', false),
      f('shop', 'Tienda online / e-commerce', false),
      f('reservations', 'Sistema de reservas online', false),
      f('faq', 'Sección de preguntas frecuentes', false),
      f('portfolio', 'Galería de portafolio', false),
      // Funcionalidades especiales
      f('whatsapp_btn', 'Botón de WhatsApp', true, 1, 'botón'),
      f(
        'contact_form',
        'Formulario de contacto',
        false,
        undefined,
        undefined,
        'No incluido; usar botón WhatsApp',
      ),
      f('map', 'Mapa de ubicación integrado', false),
      f(
        'gallery',
        'Galería de fotos de ambiente',
        false,
        undefined,
        undefined,
        'Solo fotos individuales de platos',
      ),
      f('video_banner', 'Video en portada', false),
      f('newsletter', 'Suscripción a newsletter', false),
      f('booking', 'Reservas / citas online', false),
      f('live_chat', 'Chat en vivo', false),
      f('multilang', 'Sitio multiidioma', false),
      f('reviews', 'Reseñas / testimonios', false),
      f('social_feed', 'Feed de Instagram / redes sociales', false),
      f('faq_feature', 'Sección de preguntas frecuentes', false),
      // Panel y analítica
      f(
        'cms',
        'Panel CMS para actualizar contenido',
        true,
        undefined,
        undefined,
        'Solo para platos y precios del menú',
      ),
      f('seo', 'SEO básico (meta tags, Open Graph)', true),
      f('analytics', 'Google Analytics', false),
      f('qr_code', 'Código QR personalizado imprimible', true, 1, 'QR'),
      f('email_notif', 'Notificaciones por email al negocio', false),
      f('auto_email', 'Emails automáticos al cliente', false),
      f('multi_location', 'Múltiples sucursales / ubicaciones', false),
      f('user_roles', 'Sistema de usuarios con roles', false),
      f('integrations', 'Integraciones con servicios externos', false),
      f('cv_download', 'CV / catálogo descargable', false),
      f('responsive', 'Diseño responsive (móvil, tablet, PC)', true),
      f('support_30', '30 días de soporte post-lanzamiento', true),
      f('support_60', '60 días de soporte post-lanzamiento', false),
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // LANDING EXPRESS  ·  $200
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'landing',
    name: 'Landing Express',
    tagline: 'Presencia profesional rápida',
    price: 200,
    currency: 'USD',
    deliveryDays: '8-10',
    features: [
      'Diseño profesional a medida en una sola página',
      'Adaptado a móvil, tablet y computadora',
      'Formulario de contacto para recibir consultas de clientes',
      'Botones de WhatsApp, llamada y redes sociales',
      'Carga rápida para que ningún visitante se vaya sin ver tu oferta',
      'Google Analytics incluido para ver cuánta gente te visita',
    ],
    ctaLabel: 'Empezar',
    detailedFeatures: [
      // Páginas / secciones
      f(
        'home',
        'Página principal (única)',
        true,
        1,
        'página',
        'Sitio de una sola página con secciones',
      ),
      f('about', 'Sección "Sobre mí / nosotros"', true, 1, 'sección'),
      f('services', 'Sección de servicios / productos', true, 1, 'sección'),
      f('pricing', 'Sección de precios', true, 1, 'sección'),
      f('testimonials', 'Sección de testimonios', true, 1, 'sección'),
      f('contact', 'Sección de contacto', true, 1, 'sección'),
      f('faq', 'Sección de preguntas frecuentes', true, 1, 'sección'),
      f(
        'portfolio',
        'Sección de portafolio / galería',
        false,
        undefined,
        undefined,
        'No incluido; disponible en plan Portafolio Pro',
      ),
      f('blog', 'Sección de blog / noticias', false),
      f('menu', 'Menú digital de platos', false),
      f('shop', 'Tienda online / e-commerce', false),
      f('reservations', 'Sistema de reservas online', false),
      f('location', 'Mapa de ubicación incrustado', false),
      // Funcionalidades especiales
      f('whatsapp_btn', 'Botón de WhatsApp flotante', true, 1, 'botón'),
      f('contact_form', 'Formulario de contacto', true, 1, 'formulario'),
      f(
        'map',
        'Mapa de ubicación integrado',
        false,
        undefined,
        undefined,
        'No incluido en este plan',
      ),
      f(
        'gallery',
        'Galería de fotos / videos',
        false,
        undefined,
        undefined,
        'Imágenes estáticas de sección sí; galería interactiva no',
      ),
      f('video_banner', 'Video en portada (hero)', false, undefined, undefined, 'Requiere upgrade'),
      f('newsletter', 'Suscripción a newsletter', false),
      f('booking', 'Reservas / citas online', false),
      f('live_chat', 'Chat en vivo', false),
      f('multilang', 'Sitio multiidioma', false),
      f('reviews', 'Reseñas / testimonios (sección)', true, 1, 'sección'),
      f('social_feed', 'Feed de Instagram / redes sociales', false),
      f('faq_feature', 'Preguntas frecuentes (sección)', true, 1, 'sección'),
      // Panel y analítica
      f(
        'cms',
        'Panel CMS para actualizar contenido',
        false,
        undefined,
        undefined,
        'Actualización manual vía nosotros; sin panel propio',
      ),
      f('seo', 'SEO básico (meta tags, Open Graph)', true),
      f('analytics', 'Google Analytics', true),
      f('qr_code', 'Código QR', false),
      f(
        'email_notif',
        'Notificaciones por email al negocio',
        true,
        undefined,
        undefined,
        'Vía formulario de contacto',
      ),
      f('auto_email', 'Emails automáticos al cliente', false),
      f('responsive', 'Diseño responsive (móvil, tablet, PC)', true),
      f('multi_location', 'Múltiples sucursales / ubicaciones', false),
      f('user_roles', 'Sistema de usuarios con roles', false),
      f('integrations', 'Integraciones con servicios externos', false),
      f('cv_download', 'CV / catálogo descargable', false),
      f('support_30', '30 días de soporte post-lanzamiento', true),
      f('support_60', '60 días de soporte post-lanzamiento', false),
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // BLOG PROFESIONAL  ·  $350
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'blog',
    name: 'Blog Profesional',
    tagline: 'Tu voz en internet',
    price: 350,
    currency: 'USD',
    deliveryDays: '15-19',
    features: [
      'Diseño de lectura cómoda y navegación intuitiva',
      'Categorías, etiquetas, buscador y archivo de artículos',
      'Newsletter para que tus lectores se suscriban y reciban tus novedades',
      'Sección de comentarios moderados + botones para compartir en redes',
      'SEO configurado para que Google indexe y posicione tus artículos',
      'Editor sencillo para publicar nuevos contenidos sin ayuda técnica',
    ],
    ctaLabel: 'Empezar',
    detailedFeatures: [
      // Páginas / secciones
      f('home', 'Página de inicio del blog', true, 1, 'página'),
      f('blog', 'Sección de blog con artículos', true, 'unlimited', 'artículos'),
      f('about', 'Página "Sobre el autor"', true, 1, 'página'),
      f('contact', 'Página de contacto', true, 1, 'página'),
      f('portfolio', 'Galería / portafolio de proyectos', false),
      f('services', 'Página de servicios', false),
      f('pricing', 'Página de precios', false),
      f('testimonials', 'Sección de testimonios', false),
      f('menu', 'Menú digital de platos', false),
      f('shop', 'Tienda online / e-commerce', false),
      f('reservations', 'Sistema de reservas online', false),
      f('location', 'Mapa de ubicación', false),
      f('faq', 'Sección de preguntas frecuentes', false),
      // Funcionalidades especiales
      f('whatsapp_btn', 'Botón de WhatsApp', false),
      f('contact_form', 'Formulario de contacto', true, 1, 'formulario'),
      f('map', 'Mapa de ubicación integrado', false),
      f(
        'gallery',
        'Galería de fotos / videos',
        false,
        undefined,
        undefined,
        'Imágenes dentro de artículos sí; galería interactiva no',
      ),
      f('video_banner', 'Video en portada', false),
      f('newsletter', 'Suscripción a newsletter', true, 1, 'formulario de suscripción'),
      f('booking', 'Reservas / citas online', false),
      f('live_chat', 'Chat en vivo', false),
      f('multilang', 'Sitio multiidioma', false),
      f('reviews', 'Reseñas / testimonios', false),
      f('social_feed', 'Feed de Instagram / redes sociales', true, 1, 'feed'),
      f('faq_feature', 'Preguntas frecuentes', false),
      f('comments', 'Sección de comentarios moderados', true, 1, 'sección'),
      f('search', 'Buscador interno', true, 1, 'buscador'),
      f('categories', 'Categorías y etiquetas', true, 'unlimited', 'categorías'),
      f('share_buttons', 'Botones para compartir en redes', true),
      // Panel y analítica
      f(
        'cms',
        'Panel CMS / editor de artículos',
        true,
        undefined,
        undefined,
        'Editor visual para publicar sin código',
      ),
      f('seo', 'SEO por artículo (meta tags, Schema)', true),
      f('analytics', 'Google Analytics', true),
      f('qr_code', 'Código QR', false),
      f('email_notif', 'Notificaciones por email al negocio', false),
      f(
        'auto_email',
        'Emails automáticos de newsletter',
        true,
        undefined,
        undefined,
        'Vía proveedor de newsletter como Mailchimp / Brevo',
      ),
      f('responsive', 'Diseño responsive (móvil, tablet, PC)', true),
      f('multi_location', 'Múltiples sucursales / ubicaciones', false),
      f('user_roles', 'Sistema de usuarios con roles', false),
      f('integrations', 'Integraciones con servicios externos', false),
      f('cv_download', 'CV / catálogo descargable', false),
      f('support_30', '30 días de soporte post-lanzamiento', true),
      f('support_60', '60 días de soporte post-lanzamiento', false),
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // PORTAFOLIO PRO  ·  $400
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'portfolio',
    name: 'Portafolio Pro',
    tagline: 'Tu trabajo en su mejor expresión',
    price: 400,
    currency: 'USD',
    deliveryDays: '15-20',
    highlighted: true,
    features: [
      'Diseño elegante con animaciones y carga ultrarrápida',
      'Galería de proyectos con categorías y filtros para que se encuentre fácil',
      'Página "Sobre mí" con opción de CV descargable',
      'SEO configurado para que te encuentren en Google por tu especialidad',
      'Formulario de contacto con notificaciones directas a tu email',
      'Listo para compartir en redes con imagen y descripción personalizada',
    ],
    ctaLabel: 'Empezar',
    detailedFeatures: [
      // Páginas / secciones
      f('home', 'Página de inicio', true, 1, 'página'),
      f(
        'portfolio',
        'Galería / portafolio de proyectos',
        true,
        30,
        'proyectos',
        'Más de 30 proyectos requieren upgrade',
      ),
      f('about', 'Página "Sobre mí"', true, 1, 'página'),
      f('contact', 'Página de contacto', true, 1, 'página'),
      f('services', 'Sección / página de servicios', true, 1, 'sección'),
      f('pricing', 'Sección de precios / tarifas', true, 1, 'sección'),
      f('testimonials', 'Sección de testimonios', true, 1, 'sección'),
      f(
        'blog',
        'Sección de blog',
        false,
        undefined,
        undefined,
        'No incluido; disponible en plan Blog o Empresarial',
      ),
      f('menu', 'Menú digital de platos', false),
      f('shop', 'Tienda online / e-commerce', false),
      f('reservations', 'Sistema de reservas online', false),
      f('location', 'Mapa de ubicación', false),
      f('faq', 'Sección de preguntas frecuentes', false),
      // Funcionalidades especiales
      f(
        'whatsapp_btn',
        'Botón de WhatsApp',
        false,
        undefined,
        undefined,
        'No incluido por defecto; se puede agregar bajo pedido',
      ),
      f('contact_form', 'Formulario de contacto', true, 1, 'formulario'),
      f('map', 'Mapa de ubicación integrado', false),
      f('gallery', 'Galería con categorías y filtros', true, 6, 'categorías'),
      f(
        'video_banner',
        'Video en portada (hero)',
        true,
        1,
        'video',
        'Video de presentación personal / showreel',
      ),
      f('newsletter', 'Suscripción a newsletter', false),
      f('booking', 'Reservas / citas online', false),
      f('live_chat', 'Chat en vivo', false),
      f('multilang', 'Sitio multiidioma', false),
      f('reviews', 'Reseñas / testimonios (sección)', true, 1, 'sección'),
      f('social_feed', 'Feed de Instagram / redes sociales', true, 1, 'feed'),
      f('faq_feature', 'Preguntas frecuentes', false),
      f('cv_download', 'CV / portafolio descargable (PDF)', true, 1, 'archivo'),
      // Panel y analítica
      f(
        'cms',
        'Panel CMS para gestionar proyectos',
        false,
        undefined,
        undefined,
        'Actualización manual vía nosotros; sin panel propio',
      ),
      f('seo', 'SEO por proyecto (meta tags, Schema)', true),
      f('analytics', 'Google Analytics', true),
      f('qr_code', 'Código QR', false),
      f(
        'email_notif',
        'Notificaciones por email al negocio',
        true,
        undefined,
        undefined,
        'Vía formulario de contacto',
      ),
      f('auto_email', 'Emails automáticos al cliente', false),
      f('responsive', 'Diseño responsive (móvil, tablet, PC)', true),
      f('og_tags', 'Imagen y descripción para redes (OG)', true),
      f('multi_location', 'Múltiples sucursales / ubicaciones', false),
      f('user_roles', 'Sistema de usuarios con roles', false),
      f('integrations', 'Integraciones con servicios externos', false),
      f('support_30', '30 días de soporte post-lanzamiento', true),
      f('support_60', '60 días de soporte post-lanzamiento', false),
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // RESTAURANTE PRO  ·  $500
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'restaurant',
    name: 'Restaurante Pro',
    tagline: 'Sitio completo para tu negocio gastronómico',
    price: 500,
    currency: 'USD',
    deliveryDays: '20-25',
    features: [
      'Sitio web completo: inicio, menú, reservas, galería, ubicación y contacto',
      'Menú digital con QR personalizado + panel para actualizarlo tú mismo',
      'Sistema de reservas online con confirmación automática al cliente por email',
      'Galería de fotos de ambiente, platos y eventos especiales',
      'Mapa de ubicación integrado + SEO local para aparecer en Google Maps',
      'Te avisamos de cada nueva reserva por email y WhatsApp',
    ],
    ctaLabel: 'Empezar',
    detailedFeatures: [
      // Páginas / secciones
      f('home', 'Página de inicio', true, 1, 'página'),
      f('menu', 'Menú digital con QR', true, 80, 'platos', 'Ampliable previa cotización'),
      f('reservations', 'Sistema de reservas online', true, 1, 'sistema', 'Hasta 200 reservas/mes'),
      f('gallery', 'Galería de fotos de ambiente y platos', true, 40, 'fotos'),
      f('location', 'Mapa de ubicación integrado', true, 1, 'ubicación'),
      f('contact', 'Página / sección de contacto', true, 1, 'página'),
      f('about', 'Sección "Sobre nosotros"', true, 1, 'sección'),
      f('services', 'Sección de servicios (eventos, catering)', true, 1, 'sección'),
      f(
        'testimonials',
        'Sección de testimonios',
        false,
        undefined,
        undefined,
        'No incluido; solicitar como add-on',
      ),
      f('blog', 'Sección de blog / noticias', false),
      f(
        'pricing',
        'Sección de precios',
        false,
        undefined,
        undefined,
        'El menú incluye precios por plato',
      ),
      f('shop', 'Tienda online / e-commerce', false),
      f('faq', 'Sección de preguntas frecuentes', false),
      f('portfolio', 'Galería de portafolio (creativo)', false),
      // Funcionalidades especiales
      f('whatsapp_btn', 'Botón de WhatsApp', true, 1, 'botón'),
      f('contact_form', 'Formulario de contacto', true, 1, 'formulario'),
      f('map', 'Mapa de ubicación integrado', true, 1, 'mapa'),
      f('video_banner', 'Video en portada (hero)', false, undefined, undefined, 'Requiere upgrade'),
      f('newsletter', 'Suscripción a newsletter', false),
      f('booking', 'Reservas / citas online', true, 1, 'sistema'),
      f('live_chat', 'Chat en vivo', false),
      f('multilang', 'Sitio multiidioma', false),
      f(
        'reviews',
        'Reseñas / testimonios',
        false,
        undefined,
        undefined,
        'No incluido; solicitar como add-on',
      ),
      f('social_feed', 'Feed de Instagram / redes sociales', false),
      f('faq_feature', 'Preguntas frecuentes', false),
      f('qr_code', 'Código QR personalizado imprimible', true, 1, 'QR'),
      // Panel y analítica
      f(
        'cms',
        'Panel CMS para actualizar menú',
        true,
        undefined,
        undefined,
        'Solo menú y galería; páginas estáticas no',
      ),
      f('seo', 'SEO local (Google Maps + meta tags)', true),
      f('analytics', 'Google Analytics', true),
      f(
        'email_notif',
        'Notificación por email y WhatsApp',
        true,
        undefined,
        undefined,
        'Al negocio por cada nueva reserva',
      ),
      f(
        'auto_email',
        'Email de confirmación automático',
        true,
        undefined,
        undefined,
        'Al cliente al reservar',
      ),
      f('responsive', 'Diseño responsive (móvil, tablet, PC)', true),
      f(
        'multi_location',
        'Múltiples sucursales / ubicaciones',
        false,
        undefined,
        undefined,
        'No incluido; requiere plan Custom',
      ),
      f('user_roles', 'Sistema de usuarios con roles', false),
      f('integrations', 'Integraciones con servicios externos', false),
      f('cv_download', 'CV / catálogo descargable', false),
      f('support_30', '30 días de soporte post-lanzamiento', true),
      f('support_60', '60 días de soporte post-lanzamiento', false),
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SITIO EMPRESARIAL  ·  $600
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'wp_business',
    name: 'Sitio Empresarial',
    tagline: 'Tu negocio con presencia total',
    price: 600,
    currency: 'USD',
    deliveryDays: '20-25',
    features: [
      'Sitio web completo de hasta 8 páginas diseñadas a medida',
      'Panel de administración para que actualices textos e imágenes sin ayuda',
      'Sección de noticias o blog para mantener a tus clientes informados',
      'Formularios de contacto y solicitud de cotización',
      'SEO configurado desde el primer día para posicionarte en Google',
      'Integración con Google Analytics y tus redes sociales',
    ],
    ctaLabel: 'Empezar',
    detailedFeatures: [
      // Páginas / secciones
      f('home', 'Página de inicio', true, 1, 'página'),
      f('about', 'Página "Sobre nosotros"', true, 1, 'página'),
      f('services', 'Página de servicios', true, 1, 'página'),
      f('pricing', 'Página de precios / tarifas', true, 1, 'página'),
      f('blog', 'Sección de blog / noticias', true, 1, 'sección', 'Artículos ilimitados'),
      f('contact', 'Página de contacto', true, 1, 'página'),
      f('faq', 'Página de preguntas frecuentes', true, 1, 'página'),
      f('testimonials', 'Sección de testimonios', true, 1, 'sección'),
      f('location', 'Mapa de ubicación', true, 1, 'mapa'),
      f(
        'portfolio',
        'Galería / portafolio',
        true,
        1,
        'sección',
        'Galería básica; galería avanzada con filtros requiere upgrade',
      ),
      f(
        'menu',
        'Menú digital de platos',
        false,
        undefined,
        undefined,
        'No incluido; disponible en plan Restaurante Pro',
      ),
      f(
        'shop',
        'Tienda online / e-commerce',
        false,
        undefined,
        undefined,
        'No incluido; disponible en plan Tienda Online',
      ),
      f(
        'reservations',
        'Sistema de reservas online',
        false,
        undefined,
        undefined,
        'No incluido; disponible en plan Restaurante Pro o Custom',
      ),
      // Funcionalidades especiales
      f('whatsapp_btn', 'Botón de WhatsApp flotante', true, 1, 'botón'),
      f('contact_form', 'Formularios de contacto', true, 2, 'formularios'),
      f('quote_form', 'Formulario de solicitud de cotización', true, 1, 'formulario'),
      f('map', 'Mapa de ubicación integrado', true, 1, 'mapa'),
      f(
        'gallery',
        'Galería de fotos / videos básica',
        true,
        1,
        'galería',
        'Hasta 20 fotos; sin filtros avanzados',
      ),
      f('video_banner', 'Video en portada (hero)', false, undefined, undefined, 'Requiere upgrade'),
      f(
        'newsletter',
        'Suscripción a newsletter',
        false,
        undefined,
        undefined,
        'No incluido; se puede agregar como add-on con integración externa',
      ),
      f('booking', 'Reservas / citas online', false),
      f(
        'live_chat',
        'Chat en vivo',
        false,
        undefined,
        undefined,
        'No incluido; se puede integrar widget de terceros como add-on',
      ),
      f(
        'multilang',
        'Sitio multiidioma',
        false,
        undefined,
        undefined,
        'No incluido; disponible en plan Custom',
      ),
      f('reviews', 'Reseñas / testimonios (sección)', true, 1, 'sección'),
      f(
        'social_feed',
        'Feed de Instagram / redes sociales',
        false,
        undefined,
        undefined,
        'Integración de enlaces a redes sí; feed en vivo no',
      ),
      f('faq_feature', 'Preguntas frecuentes (sección/página)', true, 1, 'página'),
      // Panel y analítica
      f(
        'cms',
        'Panel CMS para gestionar todo el sitio',
        true,
        undefined,
        undefined,
        'Hasta 8 páginas con contenido editable',
      ),
      f('seo', 'SEO completo (meta tags, Schema, sitemap)', true),
      f('analytics', 'Google Analytics', true),
      f('qr_code', 'Código QR', false),
      f(
        'email_notif',
        'Notificaciones por email al negocio',
        true,
        undefined,
        undefined,
        'Vía formularios de contacto',
      ),
      f(
        'auto_email',
        'Emails automáticos al cliente',
        false,
        undefined,
        undefined,
        'Solo confirmación de formulario básico',
      ),
      f('responsive', 'Diseño responsive (móvil, tablet, PC)', true),
      f('og_tags', 'Imagen y descripción para redes (OG)', true),
      f(
        'multi_location',
        'Múltiples sucursales / ubicaciones',
        false,
        undefined,
        undefined,
        'No incluido; requiere plan Custom',
      ),
      f('user_roles', 'Sistema de usuarios con roles', false),
      f('integrations', 'Integraciones con servicios externos', false),
      f('cv_download', 'CV / catálogo descargable', false),
      f(
        'pages_limit',
        'Páginas diseñadas a medida',
        true,
        8,
        'páginas',
        'Más de 8 páginas requieren upgrade',
      ),
      f('support_30', '30 días de soporte post-lanzamiento', true),
      f('support_60', '60 días de soporte post-lanzamiento', false),
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // TIENDA ONLINE  ·  $750
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'ecommerce_store',
    name: 'Tienda Online',
    tagline: 'Vende más en internet',
    price: 750,
    currency: 'USD',
    deliveryDays: '25-35',
    features: [
      'Tienda completa lista para vender desde el primer día',
      'Carrito de compras, checkout y múltiples métodos de pago',
      'Panel para gestionar tus pedidos, inventario y clientes',
      'Cupones de descuento y promociones configurables',
      'Emails automáticos de confirmación, pago recibido y seguimiento de pedido',
      'SEO de productos para que te encuentren en búsquedas de Google',
    ],
    ctaLabel: 'Empezar',
    detailedFeatures: [
      // Páginas / secciones
      f('home', 'Página de inicio de la tienda', true, 1, 'página'),
      f(
        'shop',
        'Catálogo / tienda con carrito',
        true,
        100,
        'productos',
        'Más de 100 productos requieren upgrade',
      ),
      f('about', 'Página "Sobre nosotros"', true, 1, 'página'),
      f('contact', 'Página de contacto', true, 1, 'página'),
      f(
        'pricing',
        'Página de precios / tarifas',
        false,
        undefined,
        undefined,
        'Los precios se gestionan por producto',
      ),
      f(
        'testimonials',
        'Sección de reseñas de productos',
        true,
        1,
        'sección',
        'Reseñas de productos por clientes registrados',
      ),
      f('faq', 'Página de preguntas frecuentes', true, 1, 'página'),
      f(
        'blog',
        'Sección de blog',
        false,
        undefined,
        undefined,
        'No incluido; disponible en plan Empresarial o Custom',
      ),
      f('portfolio', 'Galería / portafolio', false),
      f('menu', 'Menú digital de platos', false),
      f('reservations', 'Sistema de reservas / citas', false),
      f('location', 'Mapa de ubicación', true, 1, 'mapa'),
      f('services', 'Página de servicios', true, 1, 'página'),
      // Funcionalidades especiales
      f(
        'whatsapp_btn',
        'Botón de WhatsApp',
        false,
        undefined,
        undefined,
        'No incluido por defecto; se puede agregar',
      ),
      f('contact_form', 'Formulario de contacto', true, 1, 'formulario'),
      f('map', 'Mapa de ubicación integrado', true, 1, 'mapa'),
      f(
        'gallery',
        'Galería de imágenes de producto',
        true,
        'unlimited',
        'imágenes por producto',
        'Múltiples imágenes por producto',
      ),
      f('video_banner', 'Video en portada (hero)', false),
      f(
        'newsletter',
        'Suscripción a newsletter',
        false,
        undefined,
        undefined,
        'No incluido; se puede agregar como add-on',
      ),
      f('booking', 'Reservas / citas online', false),
      f('live_chat', 'Chat en vivo', false),
      f('multilang', 'Sitio multiidioma', false),
      f('reviews', 'Reseñas de productos', true, 1, 'sección'),
      f('social_feed', 'Feed de Instagram / redes sociales', false),
      f('faq_feature', 'Preguntas frecuentes', true, 1, 'página'),
      f('cart', 'Carrito de compras', true),
      f('checkout', 'Proceso de pago (checkout)', true),
      f(
        'payment_gateways',
        'Pasarelas de pago configuradas',
        true,
        3,
        'pasarelas',
        'Ej: Stripe, PayPal, transferencia. Más de 3 requieren upgrade',
      ),
      f(
        'discount_coupons',
        'Cupones de descuento',
        true,
        10,
        'cupones activos',
        'Más de 10 cupones activos requieren upgrade',
      ),
      f('inventory', 'Gestión de inventario', true),
      f('order_mgmt', 'Gestión de pedidos', true),
      f(
        'categories',
        'Categorías de productos',
        true,
        10,
        'categorías',
        'Más de 10 requieren upgrade',
      ),
      // Panel y analítica
      f('cms', 'Panel de administración de la tienda', true),
      f('seo', 'SEO de productos (meta tags, Schema)', true),
      f('analytics', 'Google Analytics + seguimiento de conversiones', true),
      f(
        'email_notif',
        'Notificaciones por email al negocio',
        true,
        undefined,
        undefined,
        'Por cada nuevo pedido',
      ),
      f(
        'auto_email',
        'Emails automáticos al cliente',
        true,
        undefined,
        undefined,
        'Confirmación, pago recibido y seguimiento de pedido',
      ),
      f('responsive', 'Diseño responsive (móvil, tablet, PC)', true),
      f('multi_location', 'Múltiples sucursales / ubicaciones', false),
      f(
        'user_roles',
        'Sistema de usuarios con roles',
        false,
        undefined,
        undefined,
        'Clientes tienen cuenta; administrador único; más roles requieren Custom',
      ),
      f(
        'integrations',
        'Integraciones con servicios externos',
        false,
        undefined,
        undefined,
        'Pasarelas de pago incluidas; otras integraciones requieren Custom',
      ),
      f('qr_code', 'Código QR', false),
      f(
        'cv_download',
        'CV / catálogo descargable',
        true,
        1,
        'catálogo',
        'Exportar catálogo de productos en PDF como add-on',
      ),
      f('support_30', '30 días de soporte post-lanzamiento', true),
      f('support_60', '60 días de soporte post-lanzamiento', false),
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // SISTEMA PERSONALIZADO  ·  $900+
  // ─────────────────────────────────────────────────────────────────────────
  {
    id: 'custom',
    name: 'Sistema Personalizado',
    tagline: 'Funcionalidades a tu medida',
    price: 900,
    currency: 'USD',
    deliveryDays: '30-50',
    features: [
      'Funcionalidades diseñadas exactamente según las necesidades de tu negocio',
      'Panel de administración propio para gestionar tu plataforma sin depender de nadie',
      'Conexión con servicios que ya usas (pagos, reservas, CRM, redes sociales…)',
      'Sistema de usuarios con roles y permisos diferenciados',
      'Capacitación para que tú y tu equipo sepan usarlo desde el primer día',
      '60 días de soporte incluidos tras el lanzamiento',
    ],
    ctaLabel: 'Solicitar cotización',
    detailedFeatures: [
      // Páginas / secciones — todo está disponible; límites según cotización
      f('home', 'Página de inicio', true, 'unlimited', 'páginas'),
      f('about', 'Página "Sobre nosotros"', true),
      f('services', 'Páginas de servicios', true, 'unlimited', 'páginas'),
      f('pricing', 'Páginas de precios', true),
      f('blog', 'Sección de blog / noticias', true, 'unlimited', 'artículos'),
      f('contact', 'Páginas de contacto', true),
      f('faq', 'Preguntas frecuentes', true),
      f('testimonials', 'Testimonios / reseñas', true),
      f('location', 'Mapa(s) de ubicación', true, 'unlimited', 'ubicaciones'),
      f('portfolio', 'Galería / portafolio', true),
      f('menu', 'Menú digital con QR', true, 'unlimited', 'platos'),
      f('shop', 'Tienda online / e-commerce', true, 'unlimited', 'productos'),
      f('reservations', 'Sistema de reservas online', true, 'unlimited', 'reservas/mes'),
      // Funcionalidades especiales — todo disponible
      f('whatsapp_btn', 'Botón de WhatsApp', true, 'unlimited', 'botones'),
      f('contact_form', 'Formularios de contacto / cotización', true, 'unlimited', 'formularios'),
      f('map', 'Mapas de ubicación integrados', true, 'unlimited', 'mapas'),
      f('gallery', 'Galerías de fotos / videos', true, 'unlimited', 'galerías'),
      f('video_banner', 'Video en portada', true, 'unlimited', 'videos'),
      f('newsletter', 'Suscripción a newsletter', true, 'unlimited', 'formularios'),
      f('booking', 'Reservas / citas online', true, 'unlimited', 'sistemas'),
      f('live_chat', 'Chat en vivo', true, 1, 'widget'),
      f('multilang', 'Sitio multiidioma', true, 'unlimited', 'idiomas'),
      f('reviews', 'Reseñas / testimonios', true, 'unlimited', 'secciones'),
      f('social_feed', 'Feed de Instagram / redes sociales', true, 'unlimited', 'feeds'),
      f('faq_feature', 'Preguntas frecuentes', true, 'unlimited', 'secciones'),
      f('cart', 'Carrito de compras', true),
      f('checkout', 'Proceso de pago (checkout)', true),
      f('payment_gateways', 'Pasarelas de pago configuradas', true, 'unlimited', 'pasarelas'),
      f('discount_coupons', 'Cupones de descuento', true, 'unlimited', 'cupones'),
      f('inventory', 'Gestión de inventario', true),
      f('order_mgmt', 'Gestión de pedidos', true),
      f('categories', 'Categorías (productos, artículos…)', true, 'unlimited', 'categorías'),
      // Panel, analítica y arquitectura
      f(
        'cms',
        'Panel de administración a medida',
        true,
        undefined,
        undefined,
        'Diseñado según flujos del negocio',
      ),
      f('seo', 'SEO completo (meta, Schema, sitemap)', true),
      f('analytics', 'Google Analytics + eventos personalizados', true),
      f('email_notif', 'Notificaciones por email al negocio', true, 'unlimited'),
      f(
        'auto_email',
        'Emails automáticos al cliente',
        true,
        'unlimited',
        'flujos',
        'Bienvenida, recordatorio, seguimiento…',
      ),
      f('responsive', 'Diseño responsive (móvil, tablet, PC)', true),
      f('og_tags', 'Imagen y descripción para redes (OG)', true),
      f('multi_location', 'Múltiples sucursales / ubicaciones', true, 'unlimited', 'sucursales'),
      f(
        'user_roles',
        'Sistema de usuarios con roles',
        true,
        'unlimited',
        'roles',
        'Hasta 3 roles incluidos; más roles se cotizan',
      ),
      f(
        'integrations',
        'Integraciones con servicios externos',
        true,
        3,
        'integraciones',
        'Más de 3 se cotizan por separado',
      ),
      f('qr_code', 'Código(s) QR personalizados', true, 'unlimited', 'QR'),
      f('cv_download', 'Documentos / catálogos descargables', true, 'unlimited', 'archivos'),
      f('training', 'Capacitación al equipo', true, 2, 'sesiones de 1 h'),
      f('support_30', '30 días de soporte post-lanzamiento', false),
      f('support_60', '60 días de soporte post-lanzamiento', true),
    ],
  },
  // ─────────────────────────────────────────────────────────────────────────
  // DISEÑO PERSONALIZADO  ·  precio variable
  // ─────────────────────────────────────────────────────────────────────────
  
];

export const PLAN_MAP: Record<string, Plan> = Object.fromEntries(PLANS.map((p) => [p.id, p]));
