import type { Plan } from '@/types';

export const PLANS: Plan[] = [
  {
    id: 'menu_qr',
    name: 'Menú Digital QR',
    tagline: 'Perfecta para tu restaurante',
    price: 150,
    currency: 'USD',
    deliveryDays: '10-12',
    features: [
      'Diseño visual acorde a tu marca y colores',
      'Hasta 50 platos con foto, descripción y precio',
      'Código QR personalizado listo para imprimir en mesa',
      'Panel sencillo para actualizar platos y precios tú mismo',
      'Botón para que tus clientes pidan directo por WhatsApp',
      'Compatible con cualquier móvil — sin descargar ninguna app',
    ],
    ctaLabel: 'Empezar',
  },
  {
    id: 'landing',
    name: 'Landing Express',
    tagline: 'Presencia profesional rápida',
    price: 200,
    currency: 'USD',
    deliveryDays: '8-10',
    features: [
      'Diseño profesional a medida en una sola página',
      'Adaptado a móvil, tablet y computadora',
      'Formulario de contacto para recibir consultas de clientes',
      'Botones de WhatsApp, llamada y redes sociales',
      'Carga rápida para que ningún visitante se vaya sin ver tu oferta',
      'Google Analytics incluido para ver cuánta gente te visita',
    ],
    ctaLabel: 'Empezar',
  },
  {
    id: 'blog',
    name: 'Blog Profesional',
    tagline: 'Tu voz en internet',
    price: 350,
    currency: 'USD',
    deliveryDays: '15-19',
    features: [
      'Diseño de lectura cómoda y navegación intuitiva',
      'Categorías, etiquetas, buscador y archivo de artículos',
      'Newsletter para que tus lectores se suscriban y reciban tus novedades',
      'Sección de comentarios moderados + botones para compartir en redes',
      'SEO configurado para que Google indexe y posicione tus artículos',
      'Editor sencillo para publicar nuevos contenidos sin ayuda técnica',
    ],
    ctaLabel: 'Empezar',
  },
  {
    id: 'portfolio',
    name: 'Portafolio Pro',
    tagline: 'Tu trabajo en su mejor expresión',
    price: 400,
    currency: 'USD',
    deliveryDays: '15-20',
    highlighted: true,
    features: [
      'Diseño elegante con animaciones y carga ultrarrápida',
      'Galería de proyectos con categorías y filtros para que se encuentre fácil',
      'Página "Sobre mí" con opción de CV descargable',
      'SEO configurado para que te encuentren en Google por tu especialidad',
      'Formulario de contacto con notificaciones directas a tu email',
      'Listo para compartir en redes con imagen y descripción personalizada',
    ],
    ctaLabel: 'Empezar',
  },
  {
    id: 'restaurant',
    name: 'Restaurante Pro',
    tagline: 'Sitio completo para tu negocio gastronómico',
    price: 500,
    currency: 'USD',
    deliveryDays: '20-25',
    features: [
      'Sitio web completo: inicio, menú, reservas, galería, ubicación y contacto',
      'Menú digital con QR personalizado + panel para actualizarlo tú mismo',
      'Sistema de reservas online con confirmación automática al cliente por email',
      'Galería de fotos de ambiente, platos y eventos especiales',
      'Mapa de ubicación integrado + SEO local para aparecer en Google Maps',
      'Te avisamos de cada nueva reserva por email y WhatsApp',
    ],
    ctaLabel: 'Empezar',
  },
  {
    id: 'wp_business',
    name: 'Sitio Empresarial',
    tagline: 'Tu negocio con presencia total',
    price: 600,
    currency: 'USD',
    deliveryDays: '20-25',
    features: [
      'Sitio web completo de hasta 8 páginas diseñadas a medida',
      'Panel de administración para que actualices textos e imágenes sin ayuda',
      'Sección de noticias o blog para mantener a tus clientes informados',
      'Formularios de contacto y solicitud de cotización',
      'SEO configurado desde el primer día para posicionarte en Google',
      'Integración con Google Analytics y tus redes sociales',
    ],
    ctaLabel: 'Empezar',
  },
  {
    id: 'ecommerce_store',
    name: 'Tienda Online',
    tagline: 'Vende más en internet',
    price: 750,
    currency: 'USD',
    deliveryDays: '25-35',
    features: [
      'Tienda completa lista para vender desde el primer día',
      'Carrito de compras, checkout y múltiples métodos de pago',
      'Panel para gestionar tus pedidos, inventario y clientes',
      'Cupones de descuento y promociones configurables',
      'Emails automáticos de confirmación, pago recibido y seguimiento de pedido',
      'SEO de productos para que te encuentren en búsquedas de Google',
    ],
    ctaLabel: 'Empezar',
  },
  {
    id: 'custom',
    name: 'Sistema Personalizado',
    tagline: 'Funcionalidades a tu medida',
    price: 900,
    currency: 'USD',
    deliveryDays: '30-50',
    features: [
      'Funcionalidades diseñadas exactamente según las necesidades de tu negocio',
      'Panel de administración propio para gestionar tu plataforma sin depender de nadie',
      'Conexión con servicios que ya usas (pagos, reservas, CRM, redes sociales…)',
      'Sistema de usuarios con roles y permisos diferenciados',
      'Capacitación para que tú y tu equipo sepan usarlo desde el primer día',
      '60 días de soporte incluidos tras el lanzamiento',
    ],
    ctaLabel: 'Solicitar cotización',
  },
];

export const PLAN_MAP: Record<string, Plan> = Object.fromEntries(PLANS.map((p) => [p.id, p]));
